// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: temporalpb/sdk.proto

package temporalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query           []*WorkflowOptions_Query      `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty"`
	Signal          []*WorkflowOptions_Signal     `protobuf:"bytes,2,rep,name=signal,proto3" json:"signal,omitempty"`
	Call            []*WorkflowOptions_Call       `protobuf:"bytes,3,rep,name=call,proto3" json:"call,omitempty"`
	SignalStart     *WorkflowOptions_SignalStart  `protobuf:"bytes,4,opt,name=signal_start,json=signalStart,proto3" json:"signal_start,omitempty"`
	WorkflowIdField string                        `protobuf:"bytes,5,opt,name=workflow_id_field,json=workflowIdField,proto3" json:"workflow_id_field,omitempty"`
	DefaultOptions  *WorkflowOptions_StartOptions `protobuf:"bytes,6,opt,name=default_options,json=defaultOptions,proto3" json:"default_options,omitempty"`
}

func (x *WorkflowOptions) Reset() {
	*x = WorkflowOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOptions) ProtoMessage() {}

func (x *WorkflowOptions) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOptions.ProtoReflect.Descriptor instead.
func (*WorkflowOptions) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowOptions) GetQuery() []*WorkflowOptions_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *WorkflowOptions) GetSignal() []*WorkflowOptions_Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *WorkflowOptions) GetCall() []*WorkflowOptions_Call {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *WorkflowOptions) GetSignalStart() *WorkflowOptions_SignalStart {
	if x != nil {
		return x.SignalStart
	}
	return nil
}

func (x *WorkflowOptions) GetWorkflowIdField() string {
	if x != nil {
		return x.WorkflowIdField
	}
	return ""
}

func (x *WorkflowOptions) GetDefaultOptions() *WorkflowOptions_StartOptions {
	if x != nil {
		return x.DefaultOptions
	}
	return nil
}

type ActivityOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultOptions *ActivityOptions_StartOptions `protobuf:"bytes,1,opt,name=default_options,json=defaultOptions,proto3" json:"default_options,omitempty"`
}

func (x *ActivityOptions) Reset() {
	*x = ActivityOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityOptions) ProtoMessage() {}

func (x *ActivityOptions) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityOptions.ProtoReflect.Descriptor instead.
func (*ActivityOptions) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityOptions) GetDefaultOptions() *ActivityOptions_StartOptions {
	if x != nil {
		return x.DefaultOptions
	}
	return nil
}

type QueryOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{2}
}

type SignalOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignalOptions) Reset() {
	*x = SignalOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalOptions) ProtoMessage() {}

func (x *SignalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalOptions.ProtoReflect.Descriptor instead.
func (*SignalOptions) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{3}
}

type CallOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CallOptions) Reset() {
	*x = CallOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallOptions) ProtoMessage() {}

func (x *CallOptions) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallOptions.ProtoReflect.Descriptor instead.
func (*CallOptions) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{4}
}

type WorkflowOptions_Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *WorkflowOptions_Query) Reset() {
	*x = WorkflowOptions_Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowOptions_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOptions_Query) ProtoMessage() {}

func (x *WorkflowOptions_Query) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOptions_Query.ProtoReflect.Descriptor instead.
func (*WorkflowOptions_Query) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WorkflowOptions_Query) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type WorkflowOptions_Signal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *WorkflowOptions_Signal) Reset() {
	*x = WorkflowOptions_Signal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowOptions_Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOptions_Signal) ProtoMessage() {}

func (x *WorkflowOptions_Signal) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOptions_Signal.ProtoReflect.Descriptor instead.
func (*WorkflowOptions_Signal) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{0, 1}
}

func (x *WorkflowOptions_Signal) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type WorkflowOptions_Call struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *WorkflowOptions_Call) Reset() {
	*x = WorkflowOptions_Call{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowOptions_Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOptions_Call) ProtoMessage() {}

func (x *WorkflowOptions_Call) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOptions_Call.ProtoReflect.Descriptor instead.
func (*WorkflowOptions_Call) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{0, 2}
}

func (x *WorkflowOptions_Call) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type WorkflowOptions_SignalStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *WorkflowOptions_SignalStart) Reset() {
	*x = WorkflowOptions_SignalStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowOptions_SignalStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOptions_SignalStart) ProtoMessage() {}

func (x *WorkflowOptions_SignalStart) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOptions_SignalStart.ProtoReflect.Descriptor instead.
func (*WorkflowOptions_SignalStart) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{0, 3}
}

func (x *WorkflowOptions_SignalStart) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type WorkflowOptions_StartOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskQueue string `protobuf:"bytes,1,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
}

func (x *WorkflowOptions_StartOptions) Reset() {
	*x = WorkflowOptions_StartOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowOptions_StartOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOptions_StartOptions) ProtoMessage() {}

func (x *WorkflowOptions_StartOptions) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOptions_StartOptions.ProtoReflect.Descriptor instead.
func (*WorkflowOptions_StartOptions) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{0, 4}
}

func (x *WorkflowOptions_StartOptions) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

type ActivityOptions_StartOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartToCloseTimeout *durationpb.Duration `protobuf:"bytes,1,opt,name=start_to_close_timeout,json=startToCloseTimeout,proto3" json:"start_to_close_timeout,omitempty"`
}

func (x *ActivityOptions_StartOptions) Reset() {
	*x = ActivityOptions_StartOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporalpb_sdk_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityOptions_StartOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityOptions_StartOptions) ProtoMessage() {}

func (x *ActivityOptions_StartOptions) ProtoReflect() protoreflect.Message {
	mi := &file_temporalpb_sdk_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityOptions_StartOptions.ProtoReflect.Descriptor instead.
func (*ActivityOptions_StartOptions) Descriptor() ([]byte, []int) {
	return file_temporalpb_sdk_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ActivityOptions_StartOptions) GetStartToCloseTimeout() *durationpb.Duration {
	if x != nil {
		return x.StartToCloseTimeout
	}
	return nil
}

var file_temporalpb_sdk_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*WorkflowOptions)(nil),
		Field:         7233,
		Name:          "temporal.sdk.workflow",
		Tag:           "bytes,7233,opt,name=workflow",
		Filename:      "temporalpb/sdk.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ActivityOptions)(nil),
		Field:         7234,
		Name:          "temporal.sdk.activity",
		Tag:           "bytes,7234,opt,name=activity",
		Filename:      "temporalpb/sdk.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*QueryOptions)(nil),
		Field:         7235,
		Name:          "temporal.sdk.query",
		Tag:           "bytes,7235,opt,name=query",
		Filename:      "temporalpb/sdk.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*SignalOptions)(nil),
		Field:         7236,
		Name:          "temporal.sdk.signal",
		Tag:           "bytes,7236,opt,name=signal",
		Filename:      "temporalpb/sdk.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*CallOptions)(nil),
		Field:         7237,
		Name:          "temporal.sdk.call",
		Tag:           "bytes,7237,opt,name=call",
		Filename:      "temporalpb/sdk.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional temporal.sdk.WorkflowOptions workflow = 7233;
	E_Workflow = &file_temporalpb_sdk_proto_extTypes[0]
	// optional temporal.sdk.ActivityOptions activity = 7234;
	E_Activity = &file_temporalpb_sdk_proto_extTypes[1]
	// optional temporal.sdk.QueryOptions query = 7235;
	E_Query = &file_temporalpb_sdk_proto_extTypes[2]
	// optional temporal.sdk.SignalOptions signal = 7236;
	E_Signal = &file_temporalpb_sdk_proto_extTypes[3]
	// optional temporal.sdk.CallOptions call = 7237;
	E_Call = &file_temporalpb_sdk_proto_extTypes[4]
)

var File_temporalpb_sdk_proto protoreflect.FileDescriptor

var file_temporalpb_sdk_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x70, 0x62, 0x2f, 0x73, 0x64, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c,
	0x2e, 0x73, 0x64, 0x6b, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb2, 0x04, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x39, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x65, 0x6d, 0x70,
	0x6f, 0x72, 0x61, 0x6c, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c,
	0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x06, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x12, 0x36, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x12, 0x4c, 0x0a, 0x0c, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x0b, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x77, 0x6f, 0x72,
	0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x64,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x53, 0x0a, 0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0e, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x19, 0x0a, 0x05, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x72, 0x65, 0x66, 0x1a, 0x1a, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65,
	0x66, 0x1a, 0x18, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x1a, 0x1f, 0x0a, 0x0b, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x1a, 0x2d, 0x0a, 0x0c,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x22, 0xc6, 0x01, 0x0a, 0x0f,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x53, 0x0a, 0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f,
	0x72, 0x61, 0x6c, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x5e, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x4e, 0x0a, 0x16, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x6f,
	0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x13, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x6f, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x3a, 0x5d, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xc1, 0x38, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72,
	0x61, 0x6c, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x88, 0x01, 0x01, 0x3a, 0x5d, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12,
	0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xc2, 0x38, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61,
	0x6c, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x88,
	0x01, 0x01, 0x3a, 0x54, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1e, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xc3, 0x38, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x88, 0x01, 0x01, 0x3a, 0x57, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xc4, 0x38, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x65, 0x6d, 0x70,
	0x6f, 0x72, 0x61, 0x6c, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x88, 0x01,
	0x01, 0x3a, 0x51, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xc5, 0x38, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x04, 0x63, 0x61, 0x6c,
	0x6c, 0x88, 0x01, 0x01, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x65, 0x74, 0x7a, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61,
	0x6c, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2d, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65,
	0x64, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_temporalpb_sdk_proto_rawDescOnce sync.Once
	file_temporalpb_sdk_proto_rawDescData = file_temporalpb_sdk_proto_rawDesc
)

func file_temporalpb_sdk_proto_rawDescGZIP() []byte {
	file_temporalpb_sdk_proto_rawDescOnce.Do(func() {
		file_temporalpb_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(file_temporalpb_sdk_proto_rawDescData)
	})
	return file_temporalpb_sdk_proto_rawDescData
}

var file_temporalpb_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_temporalpb_sdk_proto_goTypes = []interface{}{
	(*WorkflowOptions)(nil),              // 0: temporal.sdk.WorkflowOptions
	(*ActivityOptions)(nil),              // 1: temporal.sdk.ActivityOptions
	(*QueryOptions)(nil),                 // 2: temporal.sdk.QueryOptions
	(*SignalOptions)(nil),                // 3: temporal.sdk.SignalOptions
	(*CallOptions)(nil),                  // 4: temporal.sdk.CallOptions
	(*WorkflowOptions_Query)(nil),        // 5: temporal.sdk.WorkflowOptions.Query
	(*WorkflowOptions_Signal)(nil),       // 6: temporal.sdk.WorkflowOptions.Signal
	(*WorkflowOptions_Call)(nil),         // 7: temporal.sdk.WorkflowOptions.Call
	(*WorkflowOptions_SignalStart)(nil),  // 8: temporal.sdk.WorkflowOptions.SignalStart
	(*WorkflowOptions_StartOptions)(nil), // 9: temporal.sdk.WorkflowOptions.StartOptions
	(*ActivityOptions_StartOptions)(nil), // 10: temporal.sdk.ActivityOptions.StartOptions
	(*durationpb.Duration)(nil),          // 11: google.protobuf.Duration
	(*descriptorpb.MethodOptions)(nil),   // 12: google.protobuf.MethodOptions
}
var file_temporalpb_sdk_proto_depIdxs = []int32{
	5,  // 0: temporal.sdk.WorkflowOptions.query:type_name -> temporal.sdk.WorkflowOptions.Query
	6,  // 1: temporal.sdk.WorkflowOptions.signal:type_name -> temporal.sdk.WorkflowOptions.Signal
	7,  // 2: temporal.sdk.WorkflowOptions.call:type_name -> temporal.sdk.WorkflowOptions.Call
	8,  // 3: temporal.sdk.WorkflowOptions.signal_start:type_name -> temporal.sdk.WorkflowOptions.SignalStart
	9,  // 4: temporal.sdk.WorkflowOptions.default_options:type_name -> temporal.sdk.WorkflowOptions.StartOptions
	10, // 5: temporal.sdk.ActivityOptions.default_options:type_name -> temporal.sdk.ActivityOptions.StartOptions
	11, // 6: temporal.sdk.ActivityOptions.StartOptions.start_to_close_timeout:type_name -> google.protobuf.Duration
	12, // 7: temporal.sdk.workflow:extendee -> google.protobuf.MethodOptions
	12, // 8: temporal.sdk.activity:extendee -> google.protobuf.MethodOptions
	12, // 9: temporal.sdk.query:extendee -> google.protobuf.MethodOptions
	12, // 10: temporal.sdk.signal:extendee -> google.protobuf.MethodOptions
	12, // 11: temporal.sdk.call:extendee -> google.protobuf.MethodOptions
	0,  // 12: temporal.sdk.workflow:type_name -> temporal.sdk.WorkflowOptions
	1,  // 13: temporal.sdk.activity:type_name -> temporal.sdk.ActivityOptions
	2,  // 14: temporal.sdk.query:type_name -> temporal.sdk.QueryOptions
	3,  // 15: temporal.sdk.signal:type_name -> temporal.sdk.SignalOptions
	4,  // 16: temporal.sdk.call:type_name -> temporal.sdk.CallOptions
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	12, // [12:17] is the sub-list for extension type_name
	7,  // [7:12] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_temporalpb_sdk_proto_init() }
func file_temporalpb_sdk_proto_init() {
	if File_temporalpb_sdk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_temporalpb_sdk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowOptions_Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowOptions_Signal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowOptions_Call); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowOptions_SignalStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowOptions_StartOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporalpb_sdk_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityOptions_StartOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_temporalpb_sdk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_temporalpb_sdk_proto_goTypes,
		DependencyIndexes: file_temporalpb_sdk_proto_depIdxs,
		MessageInfos:      file_temporalpb_sdk_proto_msgTypes,
		ExtensionInfos:    file_temporalpb_sdk_proto_extTypes,
	}.Build()
	File_temporalpb_sdk_proto = out.File
	file_temporalpb_sdk_proto_rawDesc = nil
	file_temporalpb_sdk_proto_goTypes = nil
	file_temporalpb_sdk_proto_depIdxs = nil
}
